import type { Metadata } from "next";
import { LegalPage } from "../legal-page";
import {
  businessEmail,
  businessPhone,
  businessPhoneDisplay,
  companyName,
} from "../site-config";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `Learn how ${companyName} collects, uses, and protects information submitted through this website.`,
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPolicy() {
  return (
    <LegalPage
      eyebrow="Legal"
      title="Privacy Policy"
      summary="This policy explains what information we collect through this website, why we use it, and the choices available to you."
    >
      <section>
        <h2>1. Scope and who we are</h2>
        <p>
          This Privacy Policy applies to the website operated by {companyName}, a
          concrete-flooring company based in Charlotte, North Carolina. It covers
          information collected through this website and its estimate-request form.
          It does not replace the terms of a separate customer contract.
        </p>
      </section>

      <section>
        <h2>2. Information we collect</h2>
        <p>We may collect the following categories of information:</p>
        <ul>
          <li><strong>Information you provide:</strong> name, company, email address, phone number, requested service, project location, and project details.</li>
          <li><strong>Communications:</strong> information included in emails, calls, or follow-up conversations about your inquiry.</li>
          <li><strong>Technical information:</strong> IP address, browser and device type, referring page, requested pages, timestamps, and security logs generated by our hosting providers.</li>
          <li><strong>Optional analytics:</strong> website usage information collected through Google Analytics only after you accept analytics cookies.</li>
        </ul>
        <p>Please do not submit sensitive personal information through the estimate form.</p>
      </section>

      <section>
        <h2>3. How we use information</h2>
        <ul>
          <li>Respond to inquiries and prepare or discuss estimates.</li>
          <li>Communicate about requested flooring services.</li>
          <li>Operate, secure, troubleshoot, and improve the website.</li>
          <li>Measure website performance when analytics consent is granted.</li>
          <li>Comply with applicable law and protect our rights, customers, and business.</li>
        </ul>
      </section>

      <section>
        <h2>4. How we disclose information</h2>
        <p>
          We may disclose information to service providers that support website
          hosting, form delivery, security, analytics, and business communications;
          when required by law or a valid legal request; to protect safety or legal
          rights; or in connection with a business reorganization or transfer.
        </p>
        <p>
          We do not sell personal information, and we do not use information submitted
          through the estimate form for cross-context behavioral advertising.
        </p>
      </section>

      <section>
        <h2>5. Cookies and analytics</h2>
        <p>
          The website may use technologies necessary for operation, security, and form
          delivery. If Google Analytics is configured, it will load only after you
          select “Accept analytics.” You may decline optional analytics or change your
          choice later using the “Cookie settings” control. Declining analytics does not
          prevent you from using the website or submitting an estimate request.
        </p>
      </section>

      <section>
        <h2>6. Data retention</h2>
        <p>
          We retain inquiry and project information only for as long as reasonably
          necessary to respond, maintain business records, resolve disputes, enforce
          agreements, and meet legal obligations. Technical logs and analytics data may
          be retained according to the settings and policies of the applicable provider.
        </p>
      </section>

      <section>
        <h2>7. Data security</h2>
        <p>
          We use reasonable administrative and technical measures intended to protect
          information. No website, transmission, or storage system can be guaranteed to
          be completely secure, so please use care when submitting information online.
        </p>
      </section>

      <section>
        <h2>8. Your choices and privacy rights</h2>
        <p>
          Depending on where you live and subject to applicable exceptions, you may have
          rights to request access, correction, deletion, or a copy of personal
          information, or to withdraw analytics consent. To submit a request, email{" "}
          <a href={`mailto:${businessEmail}`}>{businessEmail}</a>. We may need to verify
          your identity before completing a request. We will not discriminate against
          you for exercising an applicable privacy right.
        </p>
      </section>

      <section>
        <h2>9. Children’s privacy</h2>
        <p>
          This website is intended for adults seeking flooring services and is not
          directed to children under 13. We do not knowingly collect personal
          information from children under 13 through the website.
        </p>
      </section>

      <section>
        <h2>10. Third-party services and links</h2>
        <p>
          The website links to third-party services such as Google, Facebook, and
          Instagram. Their privacy practices are governed by their own policies, which
          we do not control.
        </p>
      </section>

      <section>
        <h2>11. Changes to this policy</h2>
        <p>
          We may update this policy when our practices, services, or legal obligations
          change. The “Last updated” date identifies the current version.
        </p>
      </section>

      <section>
        <h2>12. Contact us</h2>
        <p>
          {companyName}<br />
          Charlotte, North Carolina<br />
          <a href={`mailto:${businessEmail}`}>{businessEmail}</a><br />
          <a href={`tel:${businessPhone}`}>{businessPhoneDisplay}</a>
        </p>
      </section>
    </LegalPage>
  );
}
